### ISSUE TITLE
Issue intercepting POSIX

### ISSUE THREAD

**Issue by nrj5k** [hariharan-devarajan/brahma#2]
Hello, I am trying to intercept posix calls
- I have installed Brahma and included it in the CMakelists
- I have intercepted the appropriate calls
- I have then enabled the Brahma wrapping in the init function

However, I get the following error.

```bash
$ LD_PRELOAD=brahma_interception.so ior
ior: symbol lookup error: brahma_interception.so: undefined symbol: _ZN6brahma5POSIX6getcwdEPcm
```

Any advice with this issue would be highly appreciated.

Can brahma wrap around posix without the init function being called from the application executable?

Thanks

**Comment by hariharan-devarajan** [comment]
looks like you have not set your LD_LIBRARY_PATH. cmake by default does dynamic linking which means it will looks for libbrahma.so at runtime. you can check that using ldd on your brahma_interception.so.

So you have two options.
1. Set LD_LIBRARY_PATH to contain the path where library is built or installed.
2. You can set the path in your CMake like this.

```
if (NOT CMAKE_INSTALL_RPATH)
    set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
    set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
endif ()
```

Let me know if this solves the issue.

**Comment by hariharan-devarajan** [comment]
So the init function is needed as we need to manage which symbols are intercepted by brahma. 

For transparent interception, you can add a library constructor and destructor and initialize and finalize brahma from there.

Note, for libraries's constructor and destructor might be called multiple times. You need to keep a global variable to only init and finalize once.

**Comment by hariharan-devarajan** [comment]
@nrj5k did this help or is it still a issue?

**Comment by hariharan-devarajan** [comment]
I have added a readme doc. As there has been no response. I am closing the issue. Please reopen if the issue still persists
